version: '3'

services:
  web:
    build: .
    command: bash -c "sleep 15 && cd /opt/app-root/current && pwd && cat Makefile && make setup-go && make run"
    volumes:
      - .:/opt/app-root/current
    ports:
      - "8081:8081"
      - "8080:8081"
